apiVersion: v1
kind: ConfigMap
metadata:
  name: void-config
  namespace: void-backend
data:
  JWT_EXPIRES_IN: "7d"
  MONGO_URI_USER: "mongodb://mongo:27017/void-users"
  MONGO_URI_PRODUCT: "mongodb://mongo:27017/void-products"
  MONGO_URI_CART: "mongodb://mongo:27017/void-carts"
  MONGO_URI_ORDER: "mongodb://mongo:27017/void-orders"
  MONGO_URI_PAYMENT: "mongodb://mongo:27017/void-payments"
  RABBITMQ_URL: "amqp://rabbitmq:5672"
  USER_SERVICE_URL: "http://user-service:3001"
  PRODUCT_SERVICE_URL: "http://product-service:3002"
  CART_SERVICE_URL: "http://cart-service:3003"
  ORDER_SERVICE_URL: "http://order-service:3004"
  PAYMENT_SERVICE_URL: "http://payment-service:3005"
